# Generated by Django 2.2.4 on 2019-12-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=100)),
            ],
        ),
    ]
