# Generated by Django 2.2.4 on 2019-12-04 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0004_acciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acciones',
            old_name='avanzar',
            new_name='pararse',
        ),
        migrations.RenameField(
            model_name='acciones',
            old_name='retroceder',
            new_name='sentarse',
        ),
    ]
