# Generated by Django 2.2.7 on 2019-12-09 07:25

from django.db import migrations, models
from datetime import date, time
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0007_movimientos_reportes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='fecha_reporte',
            field=models.DateField(default=date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportes',
            name='hora_reporte',
            field=models.TimeField(default=timezone.now),
            preserve_default=False,
        ),
    ]
