# Generated by Django 2.2.8 on 2019-12-09 17:29

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0009_auto_20191209_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='reportes',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
